name: "varlociraptor_callvariants"
description: Call variants for a given scenario specified with the varlociraptor calling grammar, preprocessed by varlociraptor preprocessing
keywords:
  - observations
  - variants
  - calling
tools:
  - "varlociraptor":
      description: "Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control."
      homepage: "https://varlociraptor.github.io/docs/estimating/"
      documentation: "https://varlociraptor.github.io/docs/calling/"
      tool_dev_url: "https://github.com/varlociraptor/varlociraptor"
      doi: "10.1186/s13059-020-01993-6"
      licence: "['GPL v3']"

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf_gz:
      type: file
      description: Compressed VCF file containing sample observations
      pattern: "*.vcf.gz"
  - bcf_gz:
      type: file
      description: BCF file containing sample observations
      pattern: "*.bcf.gz"

authors:
  - "@FriederikeHanssen"
